name: Validate SSSOM Files

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'mappings/**/*.tsv'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install sssom
      run: pip install --upgrade sssom
    
    - name: Validate SSSOM files
      run: |
        set -e
        sssom parse -m mappings/lifecycle.sssom.yml -I tsv mappings/lifecycle.sssom.tsv --output build/work/lifecycle-merged.sssom.tsv
        sssom parse -m mappings/cdi.sssom.yml -I tsv mappings/cdi.sssom.tsv --output build/work/cdi-merged.sssom.tsv
        for file in build/work/*.sssom.tsv; do
          echo "Validating $file..."
          sssom validate "$file"
        done
